version: "3.8"

# Creates the services bundle:
#    API Listener - Message Broker/Backend  - Worker
#                   Database

services: 
    db:
        image: postgres:13.2-alpine
        container_name: numapp_db
        environment: 
            POSTGRES_PASSWORD: ${DB_PASS}
            POSTGRES_DB: ${DB}
        volumes: 
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#        ports: "5432:5432" # Uncomment if connecting to the database from host.

    broker:
         image: rabbitmq:3.8-rc-management-alpine
         container_name: numapp_broker
         ports: 
             - "8080:15672"

    backend:
        image: redis:6.2.4-alpine
        container_name: numapp_backend

    listener:
        build:
            context: .
            dockerfile: Dockerfile # Provides flexibility in naming the Dockerfile
        container_name: numapp_listener
        volumes: 
            - ./app:/app
        ports:
            - "80:80"

    worker:
        image: numapp_listener
        container_name: numapp_worker
        environment: 
            DB_PASS: ${DB_PASS}
            DB: ${DB}
        command: celery -A celery_worker worker -l INFO --autoscale=10,2 --uid nobody
        depends_on:
             - "listener"
             - "broker"
             - "backend"
        volumes: 
            - ./app:/app
            